#include "KitForgePackWriter.h"
#include "KitSerializer.h"
#include "../Catalog/DownloadManager.h"

namespace
{
    juce::String uniqueSampleFileName (const juce::File& sourceFile,
                                       juce::HashMap<juce::String, int>& usedNames)
    {
        auto baseName = sourceFile.getFileName();
        const auto key = baseName.toLowerCase();

        if (! usedNames.contains (key))
        {
            usedNames.set (key, 1);
            return baseName;
        }

        const int count = ++usedNames.getReference (key);
        return sourceFile.getFileNameWithoutExtension()
             + "_" + juce::String (count)
             + sourceFile.getFileExtension();
    }

    juce::String defaultCreditsText (const juce::String& kitName)
    {
        return "Kit: " + kitName + "\n"
             + "Imported into KitForge.\n"
             + "Generated by KitForge Import on "
             + juce::Time::getCurrentTime().toString (true, true) + ".\n";
    }

    juce::String defaultLicensePlaceholder()
    {
        return "License information for this kit was not provided by the source library.\n"
             "Please verify usage rights with the original sample provider before distribution.\n";
    }
}

KitForgePackWriter::WriteResult KitForgePackWriter::writeFolder (const KitModel& kit,
                                                                  const juce::File& outputFolder,
                                                                  const WriteOptions& options) const
{
    WriteResult result;
    result.outputFolder = outputFolder;

    if (options.kitName.isEmpty())
    {
        result.errorMessage = "Kit name is required.";
        return result;
    }

    outputFolder.createDirectory();
    const auto samplesDir = outputFolder.getChildFile ("samples");

    if (! options.referenceSamplesInPlace)
        samplesDir.createDirectory();

    outputFolder.getChildFile ("artwork").createDirectory();

    KitModel kitCopy;
    kitCopy.importContents (kit);
    kitCopy.kitName = options.kitName;

    juce::HashMap<juce::String, int> usedNames;
    juce::StringArray pieceIds;

    for (const auto& piece : kitCopy.getPieces())
        pieceIds.add (piece.id);

    for (const auto& pieceId : pieceIds)
    {
        auto* piece = kitCopy.findPieceById (pieceId);

        if (piece == nullptr)
            continue;

        for (auto& art : piece->articulations)
        {
            for (auto& layer : art.layers)
            {
                for (auto& sample : layer.roundRobins.samples)
                {
                    if (options.referenceSamplesInPlace)
                        continue;

                    const juce::File sourceFile (sample.filePath);

                    if (! sourceFile.existsAsFile())
                        continue;

                    const auto destName = uniqueSampleFileName (sourceFile, usedNames);
                    const auto destFile = samplesDir.getChildFile (destName);

                    if (! destFile.existsAsFile())
                    {
                        if (! sourceFile.copyFileTo (destFile))
                        {
                            result.errorMessage = "Failed to copy sample: " + sourceFile.getFullPathName();
                            return result;
                        }
                    }

                    sample.filePath = "samples/" + destName;
                }
            }
        }
    }

    const auto kitJson = outputFolder.getChildFile ("kit.json");

    if (! KitSerializer::saveKitToFile (kitCopy, kitJson))
    {
        result.errorMessage = "Failed to write kit.json.";
        return result;
    }

    const auto credits = options.creditsText.isNotEmpty()
                           ? options.creditsText
                           : defaultCreditsText (options.kitName);
    outputFolder.getChildFile ("credits.txt").replaceWithText (credits);

    if (options.licenseText.isNotEmpty())
        outputFolder.getChildFile ("license.txt").replaceWithText (options.licenseText);
    else if (options.generatePlaceholderLicense)
        outputFolder.getChildFile ("license.txt").replaceWithText (defaultLicensePlaceholder());

    result.success = true;
    return result;
}

KitForgePackWriter::WriteResult KitForgePackWriter::writeFolderAndPack (const KitModel& kit,
                                                                         const juce::File& outputFolder,
                                                                         const juce::File& packZipFile,
                                                                         const WriteOptions& options) const
{
    auto result = writeFolder (kit, outputFolder, options);

    if (! result.success)
        return result;

    juce::String zipError;
    DownloadManager dm;

    if (! dm.createZipFromFolder (outputFolder, packZipFile, zipError))
    {
        result.errorMessage = "Folder written but failed to create .kitforgepack zip: " + zipError;
        result.success = false;
    }

    return result;
}
